services:
  - type: web
    name: vgoprint-server
    env: node
    region: oregon
    plan: free
    branch: main
    # if your code is in a subfolder, set it:
    # rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SENDINBLUE_API_KEY
        sync: false   # set the value in Render dashboard after deploy
      - key: DATABASE_URL
        fromDatabase:
          name: vgoprint-db
          property: connectionString

databases:
  - name: vgoprint-db
    region: oregon
    plan: free
